# Site settings
title: Better Api Testing in Laravel
email: hello@des.io
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
imageurl: "/images/"
url: "http://desicochrane.github.io" # the base hostname & protocol for your site
twitter_username: desicochrane
github_username:  desicochrane
highlighter: pygments
# Build settings
markdown: kramdown
exclude:
    - vendors
    - gulpfile.js
    - node_modules/
    - package.json
    - bower.json
    - npm-debug.log
    - src
